# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
